In [2]:
import numpy as np

### Scalars

In [3]:
s = 5
s

5

### Vectors

In [4]:
v = np.array([5,-2,4])
v

array([ 5, -2,  4])

### Matrices

In [5]:
m = np.array([[5,12,6],[-3,0,14]]) 
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data Types

In [6]:
type(s)

int

In [7]:
type(v)

numpy.ndarray

In [8]:
type(m)

numpy.ndarray

In [9]:
s_array = np.array(5)
s_array

array(5)

In [10]:
type(s_array)

numpy.ndarray

### Data Shapes

In [11]:
m.shape

(2, 3)

In [12]:
v.shape

(3,)

In [14]:
# reshape gives an array a new shape without changing its data
v.reshape(1,3)

array([[ 5, -2,  4]])

In [15]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [13]:
s.shape 

AttributeError: 'int' object has no attribute 'shape'

In [16]:
s_array.shape

()