In [1]:
import numpy as np

In [2]:
5+5

10

In [3]:
10-4

6

#### Addition of matrices

In [4]:
m1 = np.array([[1,2,3],[4,5,6]])
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
m3=np.array([[5,3],[2,1]])
m3

array([[5, 3],
       [2, 1]])

In [7]:
m1+m3

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

#### Exceptions

In [9]:
# This addition is allowed in python but does not make sense in linear algebra
# in Python, it adds element into array
m1+1

array([[2, 3, 4],
       [5, 6, 7]])