In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[4,5,6]]) 
A

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
s = np.array([5])
s

array([5])

In [6]:
s.T

array([5])

In [7]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [11]:
# Vectors does not have transpose
x.T

array([1, 2, 3])

In [9]:
x.shape

(3,)

In [10]:
x.T.shape

(3,)

In [14]:
# 2D array with 1 row and 3 columns can be transposed
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [13]:
x_reshaped.T

array([[1],
       [2],
       [3]])